name: Run benchmarks

on:
  workflow_dispatch:
    inputs:
      GRPC_BENCHMARK_DURATION:
        description: 'Duration of the benchmark.'
        required: false
        default: '20s'
      GRPC_BENCHMARK_WARMUP:
        description: "Duration of the warmup. Stats won't be collected."
        required: false
        default: '5s'
      GRPC_REQUEST_PAYLOAD:
        description: 'File (from [payload/](payload/)) containing the data to be sent in the client request.'
        required: false
        default: '100B'
      GRPC_SERVER_CPUS:
        description: 'Maximum number of cpus used by the server.'
        required: false
        default: '1'
      GRPC_SERVER_RAM:
        description: 'Maximum memory used by the server.'
        required: false
        default: '512m'
      GRPC_CLIENT_CONNECTIONS:
        description: 'Number of connections to use.'
        required: false
        default: '50'
      GRPC_CLIENT_CONCURRENCY:
        description: "Number of requests to run concurrently. It can't be smaller than the number of connections."
        required: false
        default: '1000'
      GRPC_CLIENT_QPS:
        description: "Rate limit, in queries per second (QPS)."
        required: false
        default: '0'
      GRPC_CLIENT_CPUS:
        description: "Maximum number of cpus used by the client."
        required: false
        default: '1'
      benchmarksToRun:
        description: "You need them to run the benchmarks"
        required: false
        # default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images for the benchmarks
        run: ./build.sh dart_grpc_bench {{ github.event.inputs.benchmarksToRun }}
      - name: Run the benchmarks
        run: ./bench.sh dart_grpc_bench {{ github.event.inputs.benchmarksToRun }}
        env:
          GRPC_BENCHMARK_DURATION: {{github.event.inputs.GRPC_BENCHMARK_DURATION}}
          GRPC_BENCHMARK_WARMUP: {{github.event.inputs.GRPC_BENCHMARK_WARMUP}}
          GRPC_REQUEST_PAYLOAD: {{github.event.inputs.GRPC_REQUEST_PAYLOAD}}
          GRPC_SERVER_CPUS: {{github.event.inputs.GRPC_SERVER_CPUS}}
          GRPC_SERVER_RAM: {{github.event.inputs.GRPC_SERVER_RAM}}
          GRPC_CLIENT_CONNECTIONS: {{github.event.inputs.GRPC_CLIENT_CONNECTIONS}}
          GRPC_CLIENT_CONCURRENCY: {{github.event.inputs.GRPC_CLIENT_CONCURRENCY}}
          GRPC_CLIENT_QPS: {{github.event.inputs.GRPC_CLIENT_QPS}}
          GRPC_CLIENT_CPUS: {{github.event.inputs.GRPC_CLIENT_CPUS}}